export default [
  {
    id: 1,
    photo_one: require("../images/houses/1.1.jpeg"),
    photo_two: require("../images/houses/1.2.jpeg"),
    photo_three: require("../images/houses/1.3.jpeg"),
    date_created: "2023-05-25T20:24:09.018+00:00",
    address: "482 Anthes Lane",
    country: "China",
    state: null,
    city: "Wenfeng Zhen",
    zipcode: null,
    category: "Mansion",
    number_of_travellers: 6,
    number_of_bedrooms: 4,
    number_of_beds: 12,
    number_of_bathrooms: 1,
    house_amenities: "Wifi",
    ad_title: "Synergized client-server neural-net",
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    user_id: 6,
  },
  {
    id: 2,
    photo_one: require("../images/houses/2.1.jpeg"),
    photo_two: require("../images/houses/2.2.jpeg"),
    photo_three: require("../images/houses/2.3.jpeg"),
    date_created: "2023-05-25T20:24:09.083+00:00",
    address: "19 Dunning Drive",
    country: "Venezuela",
    state: null,
    city: "Aroa",
    zipcode: null,
    category: "Castle",
    number_of_travellers: 5,
    number_of_bedrooms: 4,
    number_of_beds: 5,
    number_of_bathrooms: 4,
    house_amenities: "Food",
    ad_title: "Versatile methodical internet solution",
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    user_id: 2,
  },
  {
    id: 3,
    photo_one: require("../images/houses/3.1.jpeg"),
    photo_two: require("../images/houses/3.2.jpeg"),
    photo_three: require("../images/houses/3.3.jpeg"),
    date_created: "2023-05-25T20:24:09.084+00:00",
    address: "86932 Ridge Oak Hill",
    country: "Peru",
    state: null,
    city: "Ramón Castilla",
    zipcode: null,
    category: "Lodge",
    number_of_travellers: 4,
    number_of_bedrooms: 3,
    number_of_beds: 9,
    number_of_bathrooms: 3,
    house_amenities: "Heating",
    ad_title: "Expanded fault-tolerant moratorium",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    user_id: 2,
  },
  {
    id: 4,
    photo_one: require("../images/houses/4.1.jpeg"),
    photo_two: require("../images/houses/4.2.jpeg"),
    photo_three: require("../images/houses/4.3.jpeg"),
    date_created: "2023-05-25T20:24:09.086+00:00",
    address: "2719 Nevada Park",
    country: "France",
    state: "Bourgogne",
    city: "Chalon-sur-Saône",
    zipcode: "71109 CEDEX",
    category: "Bungalow",
    number_of_travellers: 3,
    number_of_bedrooms: 1,
    number_of_beds: 12,
    number_of_bathrooms: 2,
    house_amenities: "TV",
    ad_title: "Face to face multi-state protocol",
    description: "Fusce consequat. Nulla nisl. Nunc nisl.",
    user_id: 2,
  },
  {
    id: 5,
    photo_one: require("../images/houses/5.1.jpeg"),
    photo_two: require("../images/houses/5.2.jpeg"),
    photo_three: require("../images/houses/5.3.jpeg"),
    date_created: "2023-05-25T20:24:09.087+00:00",
    address: "2 Continental Crossing",
    country: "Mauritius",
    state: null,
    city: "Flic en Flac",
    zipcode: null,
    category: "Condo",
    number_of_travellers: 4,
    number_of_bedrooms: 5,
    number_of_beds: 10,
    number_of_bathrooms: 5,
    house_amenities: "Washing Machine",
    ad_title: "Upgradable 24 hour software",
    description:
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    user_id: 9,
  },
  {
    id: 6,
    photo_one: require("../images/houses/6.1.jpeg"),
    photo_two: require("../images/houses/6.2.jpeg"),
    photo_three: require("../images/houses/6.3.jpeg"),
    date_created: "2023-05-25T20:24:09.088+00:00",
    address: "209 Loftsgordon Way",
    country: "Ukraine",
    state: null,
    city: "Vyzhnytsya",
    zipcode: null,
    category: "Condo",
    number_of_travellers: 7,
    number_of_bedrooms: 5,
    number_of_beds: 5,
    number_of_bathrooms: 6,
    house_amenities: "Chimney",
    ad_title: "Face to face high-level instruction set",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    user_id: 4,
  },
  {
    id: 7,
    photo_one: require("../images/houses/7.1.jpeg"),
    photo_two: require("../images/houses/7.2.jpeg"),
    photo_three: require("../images/houses/7.3.jpeg"),
    date_created: "2023-05-25T20:24:09.089+00:00",
    address: "20269 Steensland Place",
    country: "Indonesia",
    state: null,
    city: "South Tangerang",
    zipcode: null,
    category: "House",
    number_of_travellers: 6,
    number_of_bedrooms: 2,
    number_of_beds: 9,
    number_of_bathrooms: 1,
    house_amenities: "Barbecue",
    ad_title: "Assimilated coherent local area network",
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    user_id: 9,
  },
  {
    id: 8,
    photo_one: require("../images/houses/8.1.jpeg"),
    photo_two: require("../images/houses/8.2.jpeg"),
    photo_three: require("../images/houses/8.3.jpeg"),
    date_created: "2023-05-25T20:24:09.091+00:00",
    address: "45791 Twin Pines Avenue",
    country: "Indonesia",
    state: null,
    city: "Neglasari",
    zipcode: null,
    category: "Bungalow",
    number_of_travellers: 1,
    number_of_bedrooms: 4,
    number_of_beds: 12,
    number_of_bathrooms: 6,
    house_amenities: "Dinner table",
    ad_title: "Implemented multimedia Graphical User Interface",
    description:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    user_id: 9,
  },
  {
    id: 9,
    photo_one: require("../images/houses/9.1.jpeg"),
    photo_two: require("../images/houses/9.2.jpeg"),
    photo_three: require("../images/houses/9.3.jpeg"),
    date_created: "2023-05-25T20:24:09.092+00:00",
    address: "7 Bonner Road",
    country: "Greece",
    state: null,
    city: "Ayía Triás",
    zipcode: null,
    category: "Lodge",
    number_of_travellers: 3,
    number_of_bedrooms: 5,
    number_of_beds: 1,
    number_of_bathrooms: 1,
    house_amenities: "High chair",
    ad_title: "Assimilated 4th generation open system",
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    user_id: 7,
  },
  {
    id: 10,
    photo_one: require("../images/houses/10.1.jpeg"),
    photo_two: require("../images/houses/10.2.jpeg"),
    photo_three: require("../images/houses/10.3.jpeg"),
    date_created: "2023-05-25T20:24:09.093+00:00",
    address: "71 Bobwhite Way",
    country: "Russia",
    state: null,
    city: "Stavropol’",
    zipcode: "356235",
    category: "House",
    number_of_travellers: 3,
    number_of_bedrooms: 1,
    number_of_beds: 3,
    number_of_bathrooms: 3,
    house_amenities: "Gym Access",
    ad_title: "Customizable object-oriented success",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    user_id: 8,
  },
  {
    id: 11,
    photo_one: require("../images/houses/11.1.jpeg"),
    photo_two: require("../images/houses/11.2.jpeg"),
    photo_three: require("../images/houses/11.3.jpeg"),
    date_created: "2023-05-25T20:24:09.095+00:00",
    address: "89 Cordelia Plaza",
    country: "Vietnam",
    state: null,
    city: "Si Ma Cai",
    zipcode: null,
    category: "Condo",
    number_of_travellers: 4,
    number_of_bedrooms: 2,
    number_of_beds: 7,
    number_of_bathrooms: 2,
    house_amenities: "Beach Nearby",
    ad_title: "Synchronised encompassing analyzer",
    description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    user_id: 1,
  },
  {
    id: 12,
    photo_one: require("../images/houses/12.1.jpeg"),
    photo_two: require("../images/houses/12.2.jpeg"),
    photo_three: require("../images/houses/12.3.jpeg"),
    date_created: "2023-05-25T20:24:09.097+00:00",
    address: "866 Jana Avenue",
    country: "Indonesia",
    state: null,
    city: "Galesong",
    zipcode: null,
    category: "Cabin",
    number_of_travellers: 7,
    number_of_bedrooms: 6,
    number_of_beds: 1,
    number_of_bathrooms: 1,
    house_amenities: "Garden Access",
    ad_title: "Sharable regional success",
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    user_id: 1,
  },
  {
    id: 13,
    photo_one: require("../images/houses/13.1.jpeg"),
    photo_two: require("../images/houses/13.2.jpeg"),
    photo_three: require("../images/houses/13.3.jpeg"),
    date_created: "2023-05-25T20:24:09.098+00:00",
    address: "64 Dawn Place",
    country: "Papua New Guinea",
    state: null,
    city: "Kavieng",
    zipcode: null,
    category: "Lodge",
    number_of_travellers: 3,
    number_of_bedrooms: 3,
    number_of_beds: 4,
    number_of_bathrooms: 1,
    house_amenities: "City Center",
    ad_title: "Realigned 5th generation function",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    user_id: 6,
  },
  {
    id: 14,
    photo_one: require("../images/houses/14.1.jpeg"),
    photo_two: require("../images/houses/14.2.jpeg"),
    photo_three: require("../images/houses/14.3.jpeg"),
    date_created: "2023-05-25T20:24:09.100+00:00",
    address: "55420 Bellgrove Junction",
    country: "Japan",
    state: null,
    city: "Kōriyama",
    zipcode: "963-8878",
    category: "Lodge",
    number_of_travellers: 5,
    number_of_bedrooms: 1,
    number_of_beds: 2,
    number_of_bathrooms: 4,
    house_amenities: "Private Entrance",
    ad_title: "Cross-group next generation extranet",
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    user_id: 4,
  },
  {
    id: 15,
    photo_one: require("../images/houses/15.1.jpeg"),
    photo_two: require("../images/houses/15.2.jpeg"),
    photo_three: require("../images/houses/15.3.jpeg"),
    date_created: "2023-05-25T20:24:09.101+00:00",
    address: "59365 Farragut Alley",
    country: "Portugal",
    state: "Leiria",
    city: "Monte Agudo",
    zipcode: "2425-724",
    category: "Lodge",
    number_of_travellers: 7,
    number_of_bedrooms: 4,
    number_of_beds: 12,
    number_of_bathrooms: 1,
    house_amenities: "Security System",
    ad_title: "Front-line multimedia utilisation",
    description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    user_id: 3,
  },
  {
    id: 16,
    photo_one: require("../images/houses/16.1.jpeg"),
    photo_two: require("../images/houses/16.2.jpeg"),
    photo_three: require("../images/houses/16.3.jpeg"),
    date_created: "2023-05-25T20:24:09.102+00:00",
    address: "405 Stephen Hill",
    country: "Philippines",
    state: null,
    city: "Alannay",
    zipcode: "3524",
    category: "Condo",
    number_of_travellers: 4,
    number_of_bedrooms: 1,
    number_of_beds: 4,
    number_of_bathrooms: 4,
    house_amenities: "On-Site Staff",
    ad_title: "Progressive exuding array",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    user_id: 6,
  },
  {
    id: 17,
    photo_one: require("../images/houses/17.1.jpeg"),
    photo_two: require("../images/houses/17.2.jpeg"),
    photo_three: require("../images/houses/17.3.jpeg"),
    date_created: "2023-05-25T20:24:09.104+00:00",
    address: "9 Butterfield Plaza",
    country: "China",
    state: null,
    city: "Gaohe",
    zipcode: null,
    category: "Cabin",
    number_of_travellers: 5,
    number_of_bedrooms: 4,
    number_of_beds: 6,
    number_of_bathrooms: 1,
    house_amenities: "Outdoor Space",
    ad_title: "Ameliorated regional pricing structure",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    user_id: 1,
  },
  {
    id: 18,
    photo_one: require("../images/houses/18.1.jpeg"),
    photo_two: require("../images/houses/18.2.jpeg"),
    photo_three: require("../images/houses/18.3.jpeg"),
    date_created: "2023-05-25T20:24:09.105+00:00",
    address: "69654 Erie Point",
    country: "Poland",
    state: null,
    city: "Buk",
    zipcode: "64-320",
    category: "Condo",
    number_of_travellers: 4,
    number_of_bedrooms: 2,
    number_of_beds: 2,
    number_of_bathrooms: 1,
    house_amenities: "Balcony",
    ad_title: "Fundamental 4th generation knowledge user",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    user_id: 4,
  },
  {
    id: 19,
    photo_one: require("../images/houses/19.1.jpeg"),
    photo_two: require("../images/houses/19.2.jpeg"),
    photo_three: require("../images/houses/19.3.jpeg"),
    date_created: "2023-05-25T20:24:09.107+00:00",
    address: "4055 Debs Court",
    country: "Iran",
    state: null,
    city: "Khondāb",
    zipcode: null,
    category: "Bungalow",
    number_of_travellers: 5,
    number_of_bedrooms: 6,
    number_of_beds: 3,
    number_of_bathrooms: 2,
    house_amenities: "Wifi",
    ad_title: "Public-key uniform attitude",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    user_id: 3,
  },
  {
    id: 20,
    photo_one: require("../images/houses/20.1.jpeg"),
    photo_two: require("../images/houses/20.2.jpeg"),
    photo_three: require("../images/houses/20.3.jpeg"),
    date_created: "2023-05-25T20:24:09.108+00:00",
    address: "7 Butterfield Park",
    country: "France",
    state: "Midi-Pyrénées",
    city: "Lavaur",
    zipcode: "81506 CEDEX",
    category: "Cabin",
    number_of_travellers: 7,
    number_of_bedrooms: 5,
    number_of_beds: 6,
    number_of_bathrooms: 3,
    house_amenities: "Food",
    ad_title: "Robust 24/7 website",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    user_id: 6,
  },
  {
    id: 21,
    photo_one: require("../images/houses/21.1.jpeg"),
    photo_two: require("../images/houses/21.2.jpeg"),
    photo_three: require("../images/houses/21.3.jpeg"),
    date_created: "2023-05-25T20:24:09.109+00:00",
    address: "55 Hovde Court",
    country: "Philippines",
    state: null,
    city: "Matagbak",
    zipcode: "9504",
    category: "Mansion",
    number_of_travellers: 6,
    number_of_bedrooms: 3,
    number_of_beds: 11,
    number_of_bathrooms: 4,
    house_amenities: "Heating",
    ad_title: "Innovative holistic analyzer",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    user_id: 1,
  },
  {
    id: 22,
    photo_one: require("../images/houses/22.1.jpeg"),
    photo_two: require("../images/houses/22.2.jpeg"),
    photo_three: require("../images/houses/22.3.jpeg"),
    date_created: "2023-05-25T20:24:09.111+00:00",
    address: "65 Mayer Street",
    country: "South Africa",
    state: null,
    city: "Tzaneen",
    zipcode: "0876",
    category: "Lodge",
    number_of_travellers: 7,
    number_of_bedrooms: 4,
    number_of_beds: 8,
    number_of_bathrooms: 3,
    house_amenities: "TV",
    ad_title: "Stand-alone background internet solution",
    description:
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    user_id: 10,
  },
  {
    id: 23,
    photo_one: require("../images/houses/23.1.jpeg"),
    photo_two: require("../images/houses/23.2.jpeg"),
    photo_three: require("../images/houses/23.3.jpeg"),
    date_created: "2023-05-25T20:24:09.112+00:00",
    address: "98411 Melvin Way",
    country: "Poland",
    state: null,
    city: "Pewel Wielka",
    zipcode: "34-332",
    category: "Cabin",
    number_of_travellers: 5,
    number_of_bedrooms: 6,
    number_of_beds: 6,
    number_of_bathrooms: 3,
    house_amenities: "Washing Machine",
    ad_title: "Optimized maximized encryption",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    user_id: 9,
  },
  {
    id: 24,
    photo_one: require("../images/houses/24.1.jpeg"),
    photo_two: require("../images/houses/24.2.jpeg"),
    photo_three: require("../images/houses/24.3.jpeg"),
    date_created: "2023-05-25T20:24:09.114+00:00",
    address: "302 Starling Point",
    country: "Sri Lanka",
    state: null,
    city: "Hikkaduwa",
    zipcode: "80240",
    category: "Bungalow",
    number_of_travellers: 1,
    number_of_bedrooms: 5,
    number_of_beds: 5,
    number_of_bathrooms: 2,
    house_amenities: "Chimney",
    ad_title: "Progressive 3rd generation software",
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    user_id: 4,
  },
  {
    id: 25,
    photo_one: require("../images/houses/25.1.jpeg"),
    photo_two: require("../images/houses/25.2.jpeg"),
    photo_three: require("../images/houses/25.3.jpeg"),
    date_created: "2023-05-25T20:24:09.115+00:00",
    address: "9 Steensland Terrace",
    country: "Brazil",
    state: null,
    city: "Jandira",
    zipcode: "06600-000",
    category: "Castle",
    number_of_travellers: 5,
    number_of_bedrooms: 4,
    number_of_beds: 7,
    number_of_bathrooms: 2,
    house_amenities: "Barbecue",
    ad_title: "Pre-emptive 24 hour customer loyalty",
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
    user_id: 2,
  },
  {
    id: 26,
    photo_one: require("../images/houses/26.1.jpeg"),
    photo_two: require("../images/houses/26.2.jpeg"),
    photo_three: require("../images/houses/26.3.jpeg"),
    date_created: "2023-05-25T20:24:09.117+00:00",
    address: "73956 Truax Trail",
    country: "China",
    state: null,
    city: "Shiwan",
    zipcode: null,
    category: "Chalet",
    number_of_travellers: 1,
    number_of_bedrooms: 6,
    number_of_beds: 3,
    number_of_bathrooms: 2,
    house_amenities: "Dinner table",
    ad_title: "Multi-lateral bottom-line function",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    user_id: 4,
  },
  {
    id: 27,
    photo_one: require("../images/houses/27.1.jpeg"),
    photo_two: require("../images/houses/27.2.jpeg"),
    photo_three: require("../images/houses/27.3.jpeg"),
    date_created: "2023-05-25T20:24:09.118+00:00",
    address: "652 Montana Way",
    country: "Dominican Republic",
    state: null,
    city: "Boca Chica",
    zipcode: "11102",
    category: "Condo",
    number_of_travellers: 8,
    number_of_bedrooms: 6,
    number_of_beds: 1,
    number_of_bathrooms: 5,
    house_amenities: "High chair",
    ad_title: "Stand-alone full-range projection",
    description:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.\n\nDuis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    user_id: 2,
  },
  {
    id: 28,
    photo_one: require("../images/houses/28.1.jpeg"),
    photo_two: require("../images/houses/28.2.jpeg"),
    photo_three: require("../images/houses/28.3.jpeg"),
    date_created: "2023-05-25T20:24:09.120+00:00",
    address: "08643 Pennsylvania Street",
    country: "Greece",
    state: null,
    city: "Irákleion",
    zipcode: null,
    category: "Cabin",
    number_of_travellers: 6,
    number_of_bedrooms: 3,
    number_of_beds: 8,
    number_of_bathrooms: 2,
    house_amenities: "Gym Access",
    ad_title: "Cloned bi-directional analyzer",
    description:
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    user_id: 6,
  },
  {
    id: 29,
    photo_one: require("../images/houses/29.1.jpeg"),
    photo_two: require("../images/houses/29.2.jpeg"),
    photo_three: require("../images/houses/29.3.jpeg"),
    date_created: "2023-05-25T20:24:09.121+00:00",
    address: "06075 Saint Paul Drive",
    country: "China",
    state: null,
    city: "Hengxianhe",
    zipcode: null,
    category: "Villa",
    number_of_travellers: 4,
    number_of_bedrooms: 2,
    number_of_beds: 3,
    number_of_bathrooms: 1,
    house_amenities: "Beach Nearby",
    ad_title: "Diverse static functionalities",
    description:
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    user_id: 7,
  },
  {
    id: 30,
    photo_one: require("../images/houses/30.1.jpeg"),
    photo_two: require("../images/houses/30.2.jpeg"),
    photo_three: require("../images/houses/30.3.jpeg"),
    date_created: "2023-05-25T20:24:09.122+00:00",
    address: "248 Dwight Lane",
    country: "South Korea",
    state: null,
    city: "Hongsung",
    zipcode: null,
    category: "Castle",
    number_of_travellers: 3,
    number_of_bedrooms: 3,
    number_of_beds: 8,
    number_of_bathrooms: 4,
    house_amenities: "Garden Access",
    ad_title: "Compatible web-enabled archive",
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    user_id: 4,
  },
  {
    id: 31,
    photo_one: require("../images/houses/31.1.jpeg"),
    photo_two: require("../images/houses/31.2.jpeg"),
    photo_three: require("../images/houses/31.3.jpeg"),
    date_created: "2023-05-25T20:24:09.124+00:00",
    address: "3 Jana Street",
    country: "Botswana",
    state: null,
    city: "Letsheng",
    zipcode: null,
    category: "Mansion",
    number_of_travellers: 7,
    number_of_bedrooms: 4,
    number_of_beds: 2,
    number_of_bathrooms: 4,
    house_amenities: "City Center",
    ad_title: "Upgradable needs-based workforce",
    description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    user_id: 3,
  },
  {
    id: 32,
    photo_one: require("../images/houses/32.1.jpeg"),
    photo_two: require("../images/houses/32.2.jpeg"),
    photo_three: require("../images/houses/32.3.jpeg"),
    date_created: "2023-05-25T20:24:09.125+00:00",
    address: "0 Butternut Hill",
    country: "Suriname",
    state: null,
    city: "Moengo",
    zipcode: null,
    category: "Cabin",
    number_of_travellers: 8,
    number_of_bedrooms: 4,
    number_of_beds: 4,
    number_of_bathrooms: 5,
    house_amenities: "Private Entrance",
    ad_title: "Automated analyzing migration",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    user_id: 8,
  },
  {
    id: 33,
    photo_one: require("../images/houses/33.1.jpeg"),
    photo_two: require("../images/houses/33.2.jpeg"),
    photo_three: require("../images/houses/33.3.jpeg"),
    date_created: "2023-05-25T20:24:09.126+00:00",
    address: "183 Cherokee Way",
    country: "Canada",
    state: "Ontario",
    city: "Clarence-Rockland",
    zipcode: "K4K",
    category: "Apartment",
    number_of_travellers: 1,
    number_of_bedrooms: 1,
    number_of_beds: 6,
    number_of_bathrooms: 2,
    house_amenities: "Security System",
    ad_title: "Enhanced exuding firmware",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    user_id: 3,
  },
  {
    id: 34,
    photo_one: require("../images/houses/34.1.jpeg"),
    photo_two: require("../images/houses/34.2.jpeg"),
    photo_three: require("../images/houses/34.3.jpeg"),
    date_created: "2023-05-25T20:24:09.127+00:00",
    address: "3 Carey Street",
    country: "Democratic Republic of the Congo",
    state: null,
    city: "Bolobo",
    zipcode: null,
    category: "Bungalow",
    number_of_travellers: 6,
    number_of_bedrooms: 2,
    number_of_beds: 8,
    number_of_bathrooms: 1,
    house_amenities: "On-Site Staff",
    ad_title: "Cloned discrete extranet",
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    user_id: 4,
  },
  {
    id: 35,
    photo_one: require("../images/houses/35.1.jpeg"),
    photo_two: require("../images/houses/35.2.jpeg"),
    photo_three: require("../images/houses/35.3.jpeg"),
    date_created: "2023-05-25T20:24:09.128+00:00",
    address: "38200 Helena Lane",
    country: "United states",
    state: "New York",
    city: "Brooklyn",
    zipcode: "11247",
    category: "Condo",
    number_of_travellers: 8,
    number_of_bedrooms: 4,
    number_of_beds: 3,
    number_of_bathrooms: 4,
    house_amenities: "Outdoor Space",
    ad_title: "Adaptive static system engine",
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    user_id: 8,
  },
  {
    id: 36,
    photo_one: require("../images/houses/36.1.jpeg"),
    photo_two: require("../images/houses/36.2.jpeg"),
    photo_three: require("../images/houses/36.3.jpeg"),
    date_created: "2023-05-25T20:24:09.129+00:00",
    address: "721 Evergreen Circle",
    country: "China",
    state: null,
    city: "Pantang",
    zipcode: null,
    category: "Bungalow",
    number_of_travellers: 3,
    number_of_bedrooms: 5,
    number_of_beds: 3,
    number_of_bathrooms: 4,
    house_amenities: "Balcony",
    ad_title: "Assimilated multimedia intranet",
    description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    user_id: 2,
  },
  {
    id: 37,
    photo_one: require("../images/houses/37.1.jpeg"),
    photo_two: require("../images/houses/37.2.jpeg"),
    photo_three: require("../images/houses/37.3.jpeg"),
    date_created: "2023-05-25T20:24:09.131+00:00",
    address: "12 Summit Center",
    country: "Portugal",
    state: "Lisboa",
    city: "São Pedro",
    zipcode: "2710-470",
    category: "Condo",
    number_of_travellers: 2,
    number_of_bedrooms: 5,
    number_of_beds: 9,
    number_of_bathrooms: 5,
    house_amenities: "Wifi",
    ad_title: "Decentralized analyzing website",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    user_id: 3,
  },
  {
    id: 38,
    photo_one: require("../images/houses/38.1.jpeg"),
    photo_two: require("../images/houses/38.2.jpeg"),
    photo_three: require("../images/houses/38.3.jpeg"),
    date_created: "2023-05-25T20:24:09.132+00:00",
    address: "799 Blaine Park",
    country: "China",
    state: null,
    city: "Nancheng",
    zipcode: null,
    category: "Cabin",
    number_of_travellers: 5,
    number_of_bedrooms: 4,
    number_of_beds: 4,
    number_of_bathrooms: 6,
    house_amenities: "Food",
    ad_title: "Open-source zero tolerance focus group",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    user_id: 2,
  },
  {
    id: 39,
    photo_one: require("../images/houses/39.1.jpeg"),
    photo_two: require("../images/houses/39.2.jpeg"),
    photo_three: require("../images/houses/39.3.jpeg"),
    date_created: "2023-05-25T20:24:09.133+00:00",
    address: "873 Rieder Avenue",
    country: "China",
    state: null,
    city: "Huayuanli",
    zipcode: null,
    category: "Chalet",
    number_of_travellers: 4,
    number_of_bedrooms: 2,
    number_of_beds: 2,
    number_of_bathrooms: 4,
    house_amenities: "Heating",
    ad_title: "Multi-tiered background help-desk",
    description:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    user_id: 8,
  },
  {
    id: 40,
    photo_one: require("../images/houses/40.1.jpeg"),
    photo_two: require("../images/houses/40.2.jpeg"),
    photo_three: require("../images/houses/40.3.jpeg"),
    date_created: "2023-05-25T20:24:09.134+00:00",
    address: "3 5th Terrace",
    country: "Philippines",
    state: null,
    city: "Mapaniqui",
    zipcode: "3010",
    category: "Mansion",
    number_of_travellers: 7,
    number_of_bedrooms: 3,
    number_of_beds: 1,
    number_of_bathrooms: 5,
    house_amenities: "TV",
    ad_title: "Function-based heuristic contingency",
    description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    user_id: 7,
  },
  {
    id: 41,
    photo_one: require("../images/houses/41.1.jpeg"),
    photo_two: require("../images/houses/41.2.jpeg"),
    photo_three: require("../images/houses/41.3.jpeg"),
    date_created: "2023-05-25T20:24:09.136+00:00",
    address: "78410 Granby Drive",
    country: "Indonesia",
    state: null,
    city: "Banjar Susut Kaja",
    zipcode: null,
    category: "Condo",
    number_of_travellers: 5,
    number_of_bedrooms: 6,
    number_of_beds: 11,
    number_of_bathrooms: 3,
    house_amenities: "Washing Machine",
    ad_title: "Pre-emptive scalable implementation",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    user_id: 4,
  },
  {
    id: 42,
    photo_one: require("../images/houses/42.1.jpeg"),
    photo_two: require("../images/houses/42.2.jpeg"),
    photo_three: require("../images/houses/42.3.jpeg"),
    date_created: "2023-05-25T20:24:09.137+00:00",
    address: "61 Spohn Court",
    country: "Indonesia",
    state: null,
    city: "Pule",
    zipcode: null,
    category: "Bungalow",
    number_of_travellers: 8,
    number_of_bedrooms: 1,
    number_of_beds: 3,
    number_of_bathrooms: 4,
    house_amenities: "Chimney",
    ad_title: "Intuitive didactic frame",
    description:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    user_id: 2,
  },
  {
    id: 43,
    photo_one: require("../images/houses/43.1.jpeg"),
    photo_two: require("../images/houses/43.2.jpeg"),
    photo_three: require("../images/houses/43.3.jpeg"),
    date_created: "2023-05-25T20:24:09.138+00:00",
    address: "743 Knutson Circle",
    country: "China",
    state: null,
    city: "Guandu",
    zipcode: null,
    category: "Condo",
    number_of_travellers: 7,
    number_of_bedrooms: 1,
    number_of_beds: 6,
    number_of_bathrooms: 2,
    house_amenities: "Barbecue",
    ad_title: "User-friendly static framework",
    description:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    user_id: 6,
  },
  {
    id: 44,
    photo_one: require("../images/houses/44.1.jpeg"),
    photo_two: require("../images/houses/44.2.jpeg"),
    photo_three: require("../images/houses/44.3.jpeg"),
    date_created: "2023-05-25T20:24:09.139+00:00",
    address: "9319 Scofield Point",
    country: "China",
    state: null,
    city: "Mianduhe",
    zipcode: null,
    category: "Cabin",
    number_of_travellers: 2,
    number_of_bedrooms: 6,
    number_of_beds: 5,
    number_of_bathrooms: 4,
    house_amenities: "Dinner table",
    ad_title: "Re-engineered logistical matrix",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    user_id: 3,
  },
  {
    id: 45,
    photo_one: require("../images/houses/45.1.jpeg"),
    photo_two: require("../images/houses/45.2.jpeg"),
    photo_three: require("../images/houses/45.3.jpeg"),
    date_created: "2023-05-25T20:24:09.140+00:00",
    address: "978 Welch Alley",
    country: "Netherlands",
    state: "Provincie Noord-Holland",
    city: "Beverwijk",
    zipcode: "1944",
    category: "House",
    number_of_travellers: 2,
    number_of_bedrooms: 2,
    number_of_beds: 5,
    number_of_bathrooms: 4,
    house_amenities: "High chair",
    ad_title: "Robust systemic time-frame",
    description:
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    user_id: 6,
  },
  {
    id: 46,
    photo_one: require("../images/houses/46.1.jpeg"),
    photo_two: require("../images/houses/46.2.jpeg"),
    photo_three: require("../images/houses/46.3.jpeg"),
    date_created: "2023-05-25T20:24:09.141+00:00",
    address: "99187 Oxford Way",
    country: "Brazil",
    state: null,
    city: "Campos",
    zipcode: "38250-000",
    category: "Mansion",
    number_of_travellers: 2,
    number_of_bedrooms: 5,
    number_of_beds: 6,
    number_of_bathrooms: 1,
    house_amenities: "Gym Access",
    ad_title: "Digitized holistic functionalities",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    user_id: 8,
  },
  {
    id: 47,
    photo_one: require("../images/houses/47.1.jpeg"),
    photo_two: require("../images/houses/47.2.jpeg"),
    photo_three: require("../images/houses/47.3.jpeg"),
    date_created: "2023-05-25T20:24:09.142+00:00",
    address: "17 Mitchell Center",
    country: "Thailand",
    state: null,
    city: "Hua Sai",
    zipcode: "80170",
    category: "Castle",
    number_of_travellers: 5,
    number_of_bedrooms: 4,
    number_of_beds: 2,
    number_of_bathrooms: 4,
    house_amenities: "Beach Nearby",
    ad_title: "Configurable dedicated archive",
    description:
      "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    user_id: 10,
  },
  {
    id: 48,
    photo_one: require("../images/houses/48.1.jpeg"),
    photo_two: require("../images/houses/48.2.jpeg"),
    photo_three: require("../images/houses/48.3.jpeg"),
    date_created: "2023-05-25T20:24:09.144+00:00",
    address: "985 Park Meadow Parkway",
    country: "Sri Lanka",
    state: null,
    city: "Wattegama",
    zipcode: "20810",
    category: "Lodge",
    number_of_travellers: 7,
    number_of_bedrooms: 2,
    number_of_beds: 3,
    number_of_bathrooms: 1,
    house_amenities: "Garden Access",
    ad_title: "Grass-roots regional projection",
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    user_id: 5,
  },
  {
    id: 49,
    photo_one: require("../images/houses/49.1.jpeg"),
    photo_two: require("../images/houses/49.2.jpeg"),
    photo_three: require("../images/houses/49.3.jpeg"),
    date_created: "2023-05-25T20:24:09.145+00:00",
    address: "9 Butternut Trail",
    country: "Montenegro",
    state: null,
    city: "Podgorica",
    zipcode: null,
    category: "Lodge",
    number_of_travellers: 3,
    number_of_bedrooms: 2,
    number_of_beds: 5,
    number_of_bathrooms: 6,
    house_amenities: "City Center",
    ad_title: "Multi-lateral hybrid adapter",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    user_id: 6,
  },
  {
    id: 50,
    photo_one: require("../images/houses/50.1.jpeg"),
    photo_two: require("../images/houses/50.2.jpeg"),
    photo_three: require("../images/houses/50.3.jpeg"),
    date_created: "2023-05-25T20:24:09.146+00:00",
    address: "617 Kipling Center",
    country: "Sweden",
    state: "Stockholm",
    city: "Stockholm",
    zipcode: "101 37",
    category: "Lodge",
    number_of_travellers: 1,
    number_of_bedrooms: 4,
    number_of_beds: 1,
    number_of_bathrooms: 6,
    house_amenities: "Private Entrance",
    ad_title: "Synergized 4th generation solution",
    description:
      "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
    user_id: 4,
  },
];
